<?php

namespace LogementBundle\Repository;

/**
 * FamilleAceuillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleAceuillRepository extends \Doctrine\ORM\EntityRepository
{
}
