<?php

namespace AssociationBundle\Repository;

/**
 * AssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssociationRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($term)
    {
        return $this->createQueryBuilder('Association')
            ->andWhere('Association.raisonSociale LIKE :raisonSociale')
            ->setParameter('raisonSociale', '%'.$term.'%')
            ->getQuery()
            ->execute();
    }

}
