contactmail_new :
  path:     /new
  defaults: { _controller: "ProjetProjBundle:Contactmail:new" }
  methods:  [GET, POST]

contactmail_index:
  path:     /
  defaults: { _controller: "ProjetProjBundle:Contactmail:index" }
  methods:  GET

contactmail_show:
  path:     /{id}/show
  defaults: { _controller: "ProjetProjBundle:Contactmail:show" }
  methods:  GET

contactmail_edit:
  path:     /{id}/edit
  defaults: { _controller: "ProjetProjBundle:Contactmail:edit" }
  methods:  [GET, POST]

contactmail_delete:
  path:     /{id}/delete
  defaults: { _controller: "ProjetProjBundle:Contactmail:delete" }
  methods:  DELETE

proj_formail:
  path:     /mail
  defaults: { _controller: ProjetProjBundle:Contactmail:msend}