mydemande_index:
  path:     /
  defaults: { _controller: "ProjetProjBundle:MyDemande:index" }
  methods:  GET

mydemande_show:
  path:     /{id}/show
  defaults: { _controller: "ProjetProjBundle:MyDemande:show" }
  methods:  GET

mydemande_new:
  path:     /new
  defaults: { _controller: "ProjetProjBundle:MyDemande:new" }
  methods:  [GET, POST]

mydemande_edit:
  path:     /{id}/edit
  defaults: { _controller: "ProjetProjBundle:MyDemande:edit" }
  methods:  [GET, POST]

mydemande_delete:
  path:     /{id}/delete
  defaults: { _controller: "ProjetProjBundle:MyDemande:delete" }
  methods:  DELETE