AppBundle\Entity\Benevole:
    type: entity
    table: benevole
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cin:
            type: integer
            nullable: false
            options:
                unsigned: false
        address:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        telephone:
            type: integer
            nullable: false
            options:
                unsigned: false
        niveau:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        gouvernorat:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
