AppBundle\Entity\Logement:
    type: entity
    table: logement
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adress:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        capacite:
            type: integer
            nullable: false
            options:
                unsigned: false
        resident:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
