AppBundle\Entity\MyDemande:
    type: entity
    table: my_demande
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        libelle:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    lifecycleCallbacks: {  }
