<?php

namespace Projet\ProjBundle\Repository;

/**
 * ContactmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactmailRepository extends \Doctrine\ORM\EntityRepository
{
}
