<?php

namespace Projet\ProjBundle\Repository;

/**
 * MyDemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyDemandeRepository extends \Doctrine\ORM\EntityRepository
{
}
