<?php

namespace Projet\ProjBundle\Repository;

/**
 * MyFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
