<?php

namespace Projet\ProjBundle\Repository;

/**
 * MyOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
