event_index:
    path:     /index
    defaults: { _controller: "EventBundle:Event:index" }
    methods:  [GET, POST]

event_search_result:
    path:     /search
    defaults: { _controller: "EventBundle:Event:search" }
    methods:  [GET, POST]

my_event_search_result:
    path:     /search/my/events
    defaults: { _controller: "EventBundle:Event:searchMyEvents" }
    methods:  [GET, POST]

event_my_event:
    path:     /my/events
    defaults: { _controller: "EventBundle:Event:myEvents" }
    methods:  [GET, POST]

event_show:
    path:     /{id}/show
    defaults: { _controller: "EventBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EventBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "EventBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "EventBundle:Event:delete" }

event_backOffice:
    path:     /showAdmin
    defaults: { _controller: "EventBundle:Event:showAdmin" }
participer_event:
    path:     /participer/{id}
    defaults: { _controller: "EventBundle:Event:participer" }
get_EventParticipent:
    path:     /participents/{id}
    defaults: { _controller: "EventBundle:Event:getParticipents" }

add_comment:
    path:     /addComment
    defaults: { _controller: EventBundle:Comment:addComment }

commentsPdf:
    path:     /pdf
    defaults: { _controller: EventBundle:Comment:commentsPdf }
